language: node_js
node_js:
    - 10
warnings_are_errors: false
install: npm ci
before_script: npm run test
script: npm run build
deploy:
    on:
        all_branch: true
    provider: s3
    access_key_id: $AWS_KEY
    secret_access_key: $AWS_SECRET
    bucket: 'drive.owntech.de'
    skip_cleanup: true
    acl: public_read
    local_dir: public
