os: linux
language: node_js
node_js:
    - 10
dist: trusty
warnings_are_errors: false
addons:
    apt:
        packages:
            # This is required to run new chrome on old trusty
            - libnss3

branches:
    only:
        - master
        - staging
        - production

notifications:
    slack: codeuniversity:bJz9OM3Vf7qJgNsdKsFtDC5K
    email:
        - ben.wetzel@code.berlin
        - ludwig.schubert@code.berlin

install: npm ci

stages:
    - name: unit_test
    - name: e2e_test
    # only deploy to production if there are changes on production branch
    - name: deploy_production
      if: type != pull_request AND branch = production
    # deploy every time to staging when there are change on the master or staging branches
    - name: deploy_staging
      if: type != pull_request AND branch = master OR branch = staging

jobs:
    include:
        - stage: unit_test
          before_install:
              # Enable user namespace cloning
              - 'sysctl kernel.unprivileged_userns_clone=1'
          script:
              - npm run lint
              - npm run test:coverage -- --runInBand && codecov
              - npm run test:e2e

        - stage: e2e_test
          before_install:
              # Enable user namespace cloning
              - 'sysctl kernel.unprivileged_userns_clone=1'
          script:
              - npm run test:e2e

        - stage: deploy_production
          script: CI=false NODE_OPTIONS=--max_old_space_size=8192 npm run build -- -v
          deploy:
              on:
                  branch: production
              provider: s3
              region: eu-central-1
              access_key_id: $AWS_KEY
              secret_access_key: $AWS_SECRET
              bucket: 'drive.owntech.io'
              acl: public_read
              local_dir: build

        - stage: deploy_staging
          script: CI=false  NODE_OPTIONS=--max_old_space_size=8192 npm run build -- -v
          deploy:
              on:
                  branch: staging
              provider: s3
              region: eu-central-1
              access_key_id: $AWS_KEY
              secret_access_key: $AWS_SECRET
              bucket: 'staging.drive.owntech.io'
              acl: public_read
              local_dir: build
