language: node_js
node_js:
    - 10
warnings_are_errors: false
install: npm ci
before_script: npm run test
script: CI=false npm run build
deploy:
    on:
        all_branches: true
    provider: s3
    region: eu-central-1
    endpoint: 'http://drive.owntech.de.s3-website.eu-central-1.amazonaws.com'
    access_key_id: $AWS_KEY
    secret_access_key: $AWS_SECRET
    bucket: 'drive.owntech.de'
    skip_cleanup: true
    acl: public_read
    local_dir: public
