language: node_js
node_js:
 - 8.14.0
 install: npm
 script: npm build
 deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  bucket: 'drive.owntech.de'
  skip_cleanup: true
  acl: public_read
  local_dir: public