language: node_js
node_js:
    - 10
warnings_are_errors: false

install: npm ci

script: npm run test -- -runInBand

stages:
    - name: lint
    - name: coverage
    - name: deploy_production
      if: type != pull_request AND branch = production
    - name: deploy_staging
      if: type != pull_request AND branch = staging

jobs:
    include:
        - stage: lint
          script:
              - npm run lint

        - stage: coverage
              - npm run test:coverage -- --runInBand
              - bash <(curl -s https://codecov.io/bash)

        - stage: deploy_production
          deploy:
              on:
                  branch: production
              provider: s3
              region: eu-central-1
              access_key_id: $AWS_KEY
              secret_access_key: $AWS_SECRET
              bucket: 'drive.owntech.io'
              skip_cleanup: true
              acl: public_read
              local_dir: build

        - stage: deploy_staging
          deploy:
              on:
                  branch: staging
              provider: s3
              region: eu-central-1
              access_key_id: $AWS_KEY
              secret_access_key: $AWS_SECRET
              bucket: 'drive.owntech.de'
              skip_cleanup: true
              acl: public_read
              local_dir: build
